version: "3.9"

services:

  mysql8:

    container_name: mysql8

    image: mysql:8

    ports:

      - "3307:3306"

    environment:

      MYSQL_ROOT_PASSWORD: Ci13248563..

      MYSQL_DATABASE: msvc_demo

    volumes:

      - data-mysql:/var/lib/mysql

    restart: always

    networks:

      - spring

  msvc-demo:

    container_name: msvc-demo

    image: demo:latest
    
    ports:

      - "8080:8080"

    environment:

      PORT: 8080

      DB_HOST: mysql8:3306

      DB_DATABASE: msvc_demo

      DB_USERNAME: root

      DB_PASSWORD: Ci13248563..

    networks:

      - spring

    depends_on:

      - mysql8

    restart: always
volumes:
  data-mysql:
    name: data-mysql
        
networks:
  spring:
    name: spring
